### ISSUE TITLE
[feat]: Beautify script contents

### ISSUE THREAD

**Issue by vladshcherbin** [posthtml/posthtml-beautify#234]
Hey, 👋 

Thanks for the plugin. It would be aweseme if it could beautify (fix indentation in my case) in `script` tags. Current output is:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Rollup App</title>
    <script>(function () {
  'use strict';

  function log(message) {
    console.log(message);
  }

  log('test :)');

}());</script>
  </head>
  <body></body>
</html>
```

As you can see, `script` contents has wrong indentation.

**Comment by Scrum** [comment]
@vladshcherbin Good day wherever you are now)) I am glad that someone needs this plugin.

Yes, I think you can screw some javascript formatter.

I will plan it in the near future, but maybe you can do it before me))

**Comment by vladshcherbin** [comment]
@Scrum yep, I've discovered posthtml long time ago and finally used in one of projects, also OSS one. I wish I find time to get familiar with it and help with such issues. Maybe in future. Thank you for such great projects ❤️

**Comment by Scrum** [comment]
@vladshcherbin Sorry that I could not quickly make this feature, but as they say better late than never))

**Comment by vladshcherbin** [comment]
@Scrum awesome, thank you! 😄
