### ISSUE TITLE
External script error

### ISSUE THREAD

**Issue by roose** [posthtml/posthtml-beautify#237]
I have seen #234, commit closed this issue but broke external scripts:

```
TypeError: Cannot read property 'join' of undefined
```

I think because external scripts don't have any content

**Comment by Scrum** [comment]
@roose Hi, i couldn’t make your mistake if you provide more information, maybe I can do it and I understand what needs to be fixed.

But I managed to get another error, maybe this is what you had.

when adding an empty tag I get an error
```html
<script></script>
```
```log
TypeError: "node.content is undefined"
```

Let me know if I misunderstood you or dig in the wrong direction

**Comment by roose** [comment]
Oh, thank you very much, works great!

(and sorry for my english, sometimes it’s hard for me to describe the issue)

**Comment by Scrum** [comment]
do not worry about this) Be sure to write to us if you have any suggestions or find a mistake, we will be very happy.
