### ISSUE TITLE
ci: drop support appveyor

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-beautify#242]

**Comment by anikethsaha** [comment]
seems fair 👍 

I think travis is enough. 
though we can consider github action in future if required 👍 

It can be done in https://github.com/posthtml/posthtml-beautify/pull/241 itself right ?

**Comment by Scrum** [comment]
> though we can consider github action in future if required

I'm super for github `actions`

> It can be done in #241 itself right ?

yes you can do it right there)

**Comment by anikethsaha** [comment]
> > It can be done in #241 itself right ?
> 
> yes you can do it right there)

I didn't get this!

should I submit a new PR ? cause I can push commit in that PR. 

> I'm super for github actions

yea, may be we should add action for running tests and linters without any coverage in node v10 to v14

**Comment by Scrum** [comment]
> I didn't get this!
> 
> should I submit a new PR ? cause I can push commit in that PR.

I thought that you want to make these changes to PR #241 )))
Let me know if I was wrong, so that I could close the current PR

> yea, may be we should add action for running tests and linters without any coverage in node v10 to v14

yep

**Comment by anikethsaha** [comment]
> I thought that you want to make these changes to PR #241 )))
> Let me know if I was wrong, so that I could close the current PR

no, I meant we can hold that PR  till we move to or remove appveyor. 

if its fine, then I will submit a new PR with GitHub action, and then you can update #241 then. ?

**Comment by Scrum** [comment]
ok, I understood everything, now everything will be

**Comment by Scrum** [comment]
> if its fine, then I will submit a new PR with GitHub action

go go go ))
