### ISSUE TITLE
[Feature Request]: comments formatting

### ISSUE THREAD

**Issue by anikethsaha** [posthtml/posthtml-beautify#250]
## 1. For single line comments. 

It should be in same like as `<!--` and `-->`

- bad example

```html
<!-- 
single line comment 
-->
```

- Good example: 

```html
<!-- single line comment -->
```

## 2. Multiline comments

They should always start with new line and their end of comment token (`-->`) should be in newline as well. 

- bad example

```html
<!--  multiline 
comment  -->
```

- Good example: 

```html
<!-- 
multiline 
comment 
-->
```

**Comment by Scrum** [comment]
@anikethsaha Hi, this is a very good offer

**Comment by anikethsaha** [comment]
I will try to implement this soon
